### ISSUE TITLE
AbortController does not seem to abort blob requests

### ISSUE THREAD

**Issue by scarabdesign** [mo/abortcontroller-polyfill#21]
I'm using a fetch request to get blob data from the server in the form of PNGs. If the request goes beyond a specific timeout that I've set, I am calling abort on the request (as per your instructions). The abort seems to run tough without errors, but looking at the network tab, the fetches still report "pending", eventually to return with 200 status. Is there something I'm missing?
Using updated Chrome on Linux Mint.

**Comment by scarabdesign** [comment]
Here is a screener of the network tab. I set the timeout in these cases to 30 seconds. As you can see, most of these requests spend the majority waiting. This is when I need the fetch to abort.
![network](https://user-images.githubusercontent.com/13665840/39270275-67260cfe-488a-11e8-9b30-7c64f04501c2.png)

**Comment by scarabdesign** [comment]
Ok, I figured it out! I'm using Leaflet.js to pull map tiles from my server. It pulls 6 or more tiles requests to make a layer, so I need to run abort on each of them. 

So, it seems it's working fine, although I had to remove your polyfill and update my Chrome to 66 which supports aborts natively to finally see what was going on. I'll downgrade soon and test with your code, but I don't expect it to fail...

Closing.

**Comment by mo** [comment]
This polyfill allows you to use the API for aborting fetch in your webapp without your code crashing in older browsers. However, note that this polyfill cannot actually cancel the request since the browser simply has no API for doing that. This polyfill simply ensure that the promise returned by fetch will never resolve if the request has been cancelled, and is instead rejected via an AbortError. It would be possible to implement a polyfill that actually did abort the request, but to do that one would need to reimplement and replace fetch() itself (i.e. reimplement it using XmlHttpRequest). The github/fetch polyfill does that, but they don't implement abort functionality and has no plans to support "proper abort" either as far as I know. See details here: https://github.com/github/fetch/pull/592

**Comment by scarabdesign** [comment]
Good to know. Thanks!
