### ISSUE TITLE
Polyfill breaking working implementation in Pale Moon browser

### ISSUE THREAD

**Issue by maleetz** [mo/abortcontroller-polyfill#49]
Because of the below prototype check a working implementation of AbortController in [Pale Moon browser](https://www.palemoon.org/) is overwritten with one that causes an exception.

```
  function polyfillNeeded(self) {
    if (self.__FORCE_INSTALL_ABORTCONTROLLER_POLYFILL) {
      console.log('__FORCE_INSTALL_ABORTCONTROLLER_POLYFILL=true is set, will force install polyfill');
      return true;
    } // Note that the "unfetch" minimal fetch polyfill defines fetch() without
    // defining window.Request, and this polyfill need to work on top of unfetch
    // so the below feature detection needs the !self.AbortController part.
    // The Request.prototype check is also needed because Safari versions 11.1.2
    // up to and including 12.1.x has a window.AbortController present but still
    // does NOT correctly implement abortable fetch:
    // https://bugs.webkit.org/show_bug.cgi?id=174980#c2


    return typeof self.Request === 'function' && !self.Request.prototype.hasOwnProperty('signal') || !self.AbortController;
  }
```

When using this polyfill any use of the signal in a fetch call will result in a `'signal' member of RequestInit does not implement interface AbortSignal.` exception.

To reproduce the issue you can use this snippet:

```
var controller = new AbortController();
var signal = controller.signal;
fetch(location.href, {signal});
setTimeout(function() { controller.abort(); }, 50);
```

**Comment by mo** [comment]
I tried with pale moon 28.11 now and I can't reproduce the bug

**Comment by wolfbeast** [comment]
Pale Moon has been updated to 28.12.0 which, among other things, should resolve the issues with this feature check in this polyfill.

The problem with 28.11 was that `Request.signal` would *not always* be available to code (especially in workers) due to lack of proper multithreaded handling of `signal` in particular, which would make the `self.Request.prototype.hasOwnProperty('signal')` check fail, and the polyfill would attempt to polyfill what already existed in the browser itself, causing this issue.

**Comment by mo** [comment]
thanks for the update
